"""initial schema

Revision ID: ee4e5b7811bd
Revises: 
Create Date: 2026-07-12 21:58:24.136411
"""
from alembic import op
import sqlalchemy as sa
import app.db.base  # custom GUID type used by columns


revision = 'ee4e5b7811bd'
down_revision = None
branch_labels = None
depends_on = None

# Shared ENUM types are created once and dropped in downgrade (reversibility).
from sqlalchemy.dialects import postgresql

content_status_enum = postgresql.ENUM('draft', 'in_review', 'published', 'archived', name='content_status', create_type=False)
user_role_enum = postgresql.ENUM('user', 'beta_tester', 'moderator', 'content_editor', 'admin', 'owner', name='user_role', create_type=False)
user_status_enum = postgresql.ENUM('active', 'suspended', 'deleted', name='user_status', create_type=False)
item_type_enum = postgresql.ENUM('vocabulary', 'grammar', name='item_type', create_type=False)
practice_category_enum = postgresql.ENUM('sentences', 'listening', 'speaking', name='practice_category', create_type=False)
leech_state_enum = postgresql.ENUM('none', 'watch', 'leech', 'critical', name='leech_state', create_type=False)
curriculum_mode_enum = postgresql.ENUM('default_dispersed', 'grammar_batch', 'fully_dispersed', name='curriculum_mode', create_type=False)
lesson_kind_enum = postgresql.ENUM('themed_vocab', 'grammar_batch', 'mixed', name='lesson_kind', create_type=False)
gram_gender_enum = postgresql.ENUM('masculine', 'feminine', 'both', 'neutral', 'none', name='gram_gender', create_type=False)
article_enum = postgresql.ENUM('el', 'la', 'los', 'las', 'un', 'una', 'none', name='article', create_type=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    content_status_enum.create(op.get_bind(), checkfirst=True)
    user_role_enum.create(op.get_bind(), checkfirst=True)
    user_status_enum.create(op.get_bind(), checkfirst=True)
    item_type_enum.create(op.get_bind(), checkfirst=True)
    practice_category_enum.create(op.get_bind(), checkfirst=True)
    leech_state_enum.create(op.get_bind(), checkfirst=True)
    curriculum_mode_enum.create(op.get_bind(), checkfirst=True)
    lesson_kind_enum.create(op.get_bind(), checkfirst=True)
    gram_gender_enum.create(op.get_bind(), checkfirst=True)
    article_enum.create(op.get_bind(), checkfirst=True)
    op.create_table('audio_assets',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('storage_path', sa.String(length=400), nullable=False),
    sa.Column('content_type', sa.String(length=40), nullable=False),
    sa.Column('content_id', app.db.base.GUID(), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('voice_id', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('status', content_status_enum, nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_path')
    )
    op.create_table('dashboard_widgets',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('languages',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('native_name', sa.String(length=60), nullable=False),
    sa.Column('stage_names', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('auth_provider_id', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('role', user_role_enum, nullable=False),
    sa.Column('status', user_status_enum, nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_provider_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('admin_audit_logs',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('actor_id', app.db.base.GUID(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_table', sa.String(length=60), nullable=False),
    sa.Column('target_id', app.db.base.GUID(), nullable=True),
    sa.Column('before', sa.JSON(), nullable=False),
    sa.Column('after', sa.JSON(), nullable=False),
    sa.Column('ip_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_audit_logs_actor_id'), ['actor_id'], unique=False)

    op.create_table('auth_sessions',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=128), nullable=False),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('ip_hash', sa.String(length=128), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('rotated_from_session_id', app.db.base.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('changelog_entries',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('author_id', app.db.base.GUID(), nullable=True),
    sa.Column('status', content_status_enum, nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_imports',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('created_by', app.db.base.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_versions',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('table_name', sa.String(length=60), nullable=False),
    sa.Column('row_id', app.db.base.GUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('changed_by', app.db.base.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_versions_row_id'), ['row_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_versions_table_name'), ['table_name'], unique=False)

    op.create_table('deletion_approvals',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('target_table', sa.String(length=60), nullable=False),
    sa.Column('target_id', app.db.base.GUID(), nullable=False),
    sa.Column('requested_by', app.db.base.GUID(), nullable=False),
    sa.Column('approved_by', app.db.base.GUID(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_tickets',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('route', sa.String(length=300), nullable=False),
    sa.Column('browser', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('screenshot_asset_id', app.db.base.GUID(), nullable=True),
    sa.Column('state', sa.String(length=12), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_prompts',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('language_id', app.db.base.GUID(), nullable=False),
    sa.Column('text_en', sa.Text(), nullable=False),
    sa.Column('text_target', sa.Text(), nullable=False),
    sa.Column('active_on', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('active_on', name='uq_prompt_active_on')
    )
    op.create_table('modules',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('language_id', app.db.base.GUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', content_status_enum, nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_id', 'position', name='uq_module_pos')
    )
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modules_language_id'), ['language_id'], unique=False)

    op.create_table('points_events',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('source_table', sa.String(length=40), nullable=False),
    sa.Column('source_id', app.db.base.GUID(), nullable=True),
    sa.Column('idempotency_key', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_points_idem')
    )
    with op.batch_alter_table('points_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_points_events_user_id'), ['user_id'], unique=False)

    op.create_table('practice_sessions',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('practice_type', sa.String(length=30), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=12), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('profiles',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('xp_total', sa.BigInteger(), nullable=False),
    sa.Column('points_balance', sa.BigInteger(), nullable=False),
    sa.Column('rank_level', sa.Integer(), nullable=False),
    sa.Column('streak_current', sa.Integer(), nullable=False),
    sa.Column('streak_best', sa.Integer(), nullable=False),
    sa.Column('streak_type', sa.String(length=30), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('onboarding_completed_at', sa.DateTime(), nullable=True),
    sa.Column('immersion_unlocked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('review_sessions',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=12), nullable=False),
    sa.Column('queue_snapshot', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('sentences',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('language_id', app.db.base.GUID(), nullable=False),
    sa.Column('text_es', sa.Text(), nullable=False),
    sa.Column('text_en', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=12), nullable=False),
    sa.Column('audio_asset_id', app.db.base.GUID(), nullable=True),
    sa.Column('status', content_status_enum, nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['audio_assets.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sentences_language_id'), ['language_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=80), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_changelog_reads',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_item_practice_stages',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('item_type', item_type_enum, nullable=False),
    sa.Column('item_id', app.db.base.GUID(), nullable=False),
    sa.Column('category', practice_category_enum, nullable=False),
    sa.Column('stage', sa.SmallInteger(), nullable=False),
    sa.Column('stage_reached_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_type', 'item_id', 'category', name='uq_user_item_practice')
    )
    with op.batch_alter_table('user_item_practice_stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_item_practice_stages_user_id'), ['user_id'], unique=False)

    op.create_table('user_item_progress',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('item_type', item_type_enum, nullable=False),
    sa.Column('item_id', app.db.base.GUID(), nullable=False),
    sa.Column('srs_stage', sa.SmallInteger(), nullable=False),
    sa.Column('next_review_at', sa.DateTime(), nullable=True),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.Column('lesson_completed_at', sa.DateTime(), nullable=True),
    sa.Column('fluent_at', sa.DateTime(), nullable=True),
    sa.Column('perfect_at', sa.DateTime(), nullable=True),
    sa.Column('meaning_passed_pending', sa.Boolean(), nullable=False),
    sa.Column('reading_passed_pending', sa.Boolean(), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('total_incorrect', sa.Integer(), nullable=False),
    sa.Column('recent_results', sa.JSON(), nullable=False),
    sa.Column('leech_score', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('leech_state', leech_state_enum, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_type', 'item_id', name='uq_user_item')
    )
    with op.batch_alter_table('user_item_progress', schema=None) as batch_op:
        batch_op.create_index('ix_uip_due', ['user_id', 'next_review_at'], unique=False)

    op.create_table('user_settings',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('theme', sa.String(length=10), nullable=False),
    sa.Column('font_size', sa.String(length=10), nullable=False),
    sa.Column('color_theme', sa.String(length=30), nullable=False),
    sa.Column('lesson_batch_size', sa.Integer(), nullable=False),
    sa.Column('review_order', sa.String(length=20), nullable=False),
    sa.Column('curriculum_mode', curriculum_mode_enum, nullable=False),
    sa.Column('back_to_back', sa.Boolean(), nullable=False),
    sa.Column('back_to_back_order', sa.String(length=10), nullable=False),
    sa.Column('show_srs_indicator', sa.Boolean(), nullable=False),
    sa.Column('leech_threshold', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('review_batch_enabled', sa.Boolean(), nullable=False),
    sa.Column('review_batch_size', sa.Integer(), nullable=False),
    sa.Column('reveal_full_answer', sa.Boolean(), nullable=False),
    sa.Column('allow_cheating', sa.Boolean(), nullable=False),
    sa.Column('allow_skipping', sa.Boolean(), nullable=False),
    sa.Column('undo_enabled', sa.Boolean(), nullable=False),
    sa.Column('accept_user_synonyms', sa.Boolean(), nullable=False),
    sa.Column('intermissions_enabled', sa.Boolean(), nullable=False),
    sa.Column('immersion_mode', sa.Boolean(), nullable=False),
    sa.Column('dialect', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_synonyms',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('item_type', item_type_enum, nullable=False),
    sa.Column('item_id', app.db.base.GUID(), nullable=False),
    sa.Column('synonym', sa.String(length=200), nullable=False),
    sa.Column('normalized', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_type', 'item_id', 'normalized', name='uq_user_syn')
    )
    with op.batch_alter_table('user_synonyms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_synonyms_user_id'), ['user_id'], unique=False)

    op.create_table('user_widget_layouts',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('layout', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('xp_events',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('source_table', sa.String(length=40), nullable=False),
    sa.Column('source_id', app.db.base.GUID(), nullable=True),
    sa.Column('idempotency_key', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_xp_idem')
    )
    with op.batch_alter_table('xp_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_xp_events_user_id'), ['user_id'], unique=False)

    op.create_table('grammar_points',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('language_id', app.db.base.GUID(), nullable=False),
    sa.Column('module_id', app.db.base.GUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('translation', sa.String(length=200), nullable=False),
    sa.Column('structure_pattern', sa.String(length=300), nullable=False),
    sa.Column('part_of_speech', sa.String(length=40), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=False),
    sa.Column('explanation_rich', sa.Text(), nullable=False),
    sa.Column('accepted_answers', sa.JSON(), nullable=False),
    sa.Column('rejected_answers', sa.JSON(), nullable=False),
    sa.Column('synonyms', sa.JSON(), nullable=False),
    sa.Column('unlocks', sa.JSON(), nullable=False),
    sa.Column('audio_asset_id', app.db.base.GUID(), nullable=True),
    sa.Column('source_import_id', app.db.base.GUID(), nullable=True),
    sa.Column('status', content_status_enum, nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['audio_assets.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grammar_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grammar_points_language_id'), ['language_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grammar_points_module_id'), ['module_id'], unique=False)

    op.create_table('intermissions',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('module_id', app.db.base.GUID(), nullable=True),
    sa.Column('trigger', sa.JSON(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body_rich', sa.Text(), nullable=False),
    sa.Column('status', content_status_enum, nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_entries',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('prompt_id', app.db.base.GUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('body_draft', sa.Text(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('visibility', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['journal_prompts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_user_id'), ['user_id'], unique=False)

    op.create_table('lessons',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('module_id', app.db.base.GUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('kind', lesson_kind_enum, nullable=False),
    sa.Column('theme_title', sa.String(length=120), nullable=False),
    sa.Column('status', content_status_enum, nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'position', name='uq_lesson_pos')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_module_id'), ['module_id'], unique=False)

    op.create_table('review_answers',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('session_id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('item_type', item_type_enum, nullable=False),
    sa.Column('item_id', app.db.base.GUID(), nullable=False),
    sa.Column('prompt_direction', sa.String(length=10), nullable=False),
    sa.Column('prompt_kind', sa.String(length=10), nullable=False),
    sa.Column('submitted_answer', sa.Text(), nullable=False),
    sa.Column('normalized_answer', sa.Text(), nullable=False),
    sa.Column('original_correct', sa.Boolean(), nullable=False),
    sa.Column('final_correct', sa.Boolean(), nullable=False),
    sa.Column('typo_forgiven', sa.Boolean(), nullable=False),
    sa.Column('synonym_matched', sa.Boolean(), nullable=False),
    sa.Column('warning_flags', sa.JSON(), nullable=False),
    sa.Column('undo_used', sa.Boolean(), nullable=False),
    sa.Column('undo_reason', sa.Text(), nullable=True),
    sa.Column('srs_stage_before', sa.SmallInteger(), nullable=True),
    sa.Column('srs_stage_after', sa.SmallInteger(), nullable=True),
    sa.Column('pair_incomplete', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', app.db.base.GUID(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['review_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_review_answer_idem')
    )
    with op.batch_alter_table('review_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_answers_session_id'), ['session_id'], unique=False)

    op.create_table('sentence_links',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('sentence_id', app.db.base.GUID(), nullable=False),
    sa.Column('item_type', item_type_enum, nullable=False),
    sa.Column('item_id', app.db.base.GUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('cloze_answer', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sentence_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sentence_links_sentence_id'), ['sentence_id'], unique=False)

    op.create_table('srs_reviews',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('item_type', item_type_enum, nullable=False),
    sa.Column('item_id', app.db.base.GUID(), nullable=False),
    sa.Column('session_id', app.db.base.GUID(), nullable=True),
    sa.Column('stage_before', sa.SmallInteger(), nullable=False),
    sa.Column('stage_after', sa.SmallInteger(), nullable=False),
    sa.Column('wrong_answer_count', sa.SmallInteger(), nullable=False),
    sa.Column('promoted', sa.Boolean(), nullable=False),
    sa.Column('penalty_factor', sa.SmallInteger(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['review_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('srs_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_srs_reviews_user_id'), ['user_id'], unique=False)

    op.create_table('user_module_state',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('module_id', app.db.base.GUID(), nullable=False),
    sa.Column('curriculum_mode_locked', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'module_id', name='uq_user_module')
    )
    with op.batch_alter_table('user_module_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_module_state_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_module_state_user_id'), ['user_id'], unique=False)

    op.create_table('vocabulary_items',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('language_id', app.db.base.GUID(), nullable=False),
    sa.Column('module_id', app.db.base.GUID(), nullable=False),
    sa.Column('term', sa.String(length=120), nullable=False),
    sa.Column('normalized_term', sa.String(length=120), nullable=False),
    sa.Column('primary_translation', sa.String(length=200), nullable=False),
    sa.Column('part_of_speech', sa.String(length=40), nullable=False),
    sa.Column('difficulty_rank', sa.Integer(), nullable=False),
    sa.Column('pronunciation', sa.String(length=120), nullable=False),
    sa.Column('ipa', sa.String(length=120), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('grammatical_gender', gram_gender_enum, nullable=False),
    sa.Column('article', article_enum, nullable=False),
    sa.Column('accepted_answers', sa.JSON(), nullable=False),
    sa.Column('rejected_answers', sa.JSON(), nullable=False),
    sa.Column('synonyms', sa.JSON(), nullable=False),
    sa.Column('variations', sa.JSON(), nullable=False),
    sa.Column('castilian_variant', sa.String(length=200), nullable=False),
    sa.Column('latam_variant', sa.String(length=200), nullable=False),
    sa.Column('audio_asset_id', app.db.base.GUID(), nullable=True),
    sa.Column('source_import_id', app.db.base.GUID(), nullable=True),
    sa.Column('status', content_status_enum, nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("article = 'none' OR part_of_speech = 'noun'", name='ck_article_only_for_nouns'),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['audio_assets.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vocabulary_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocabulary_items_language_id'), ['language_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vocabulary_items_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vocabulary_items_normalized_term'), ['normalized_term'], unique=False)

    op.create_table('lesson_items',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('lesson_id', app.db.base.GUID(), nullable=False),
    sa.Column('curriculum_mode', sa.String(length=30), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('item_type', item_type_enum, nullable=False),
    sa.Column('item_id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'curriculum_mode', 'position', name='uq_lessonitem_pos')
    )
    with op.batch_alter_table('lesson_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_items_lesson_id'), ['lesson_id'], unique=False)

    op.create_table('user_intermission_views',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('intermission_id', app.db.base.GUID(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['intermission_id'], ['intermissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'intermission_id', name='uq_user_interm')
    )
    with op.batch_alter_table('user_intermission_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_intermission_views_user_id'), ['user_id'], unique=False)

    op.create_table('verbs_meta',
    sa.Column('vocabulary_item_id', app.db.base.GUID(), nullable=False),
    sa.Column('conjugation_class', sa.String(length=10), nullable=False),
    sa.Column('is_regular', sa.Boolean(), nullable=False),
    sa.Column('conjugations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vocabulary_item_id'], ['vocabulary_items.id'], ),
    sa.PrimaryKeyConstraint('vocabulary_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verbs_meta')
    with op.batch_alter_table('user_intermission_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_intermission_views_user_id'))

    op.drop_table('user_intermission_views')
    with op.batch_alter_table('lesson_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_items_lesson_id'))

    op.drop_table('lesson_items')
    with op.batch_alter_table('vocabulary_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocabulary_items_normalized_term'))
        batch_op.drop_index(batch_op.f('ix_vocabulary_items_module_id'))
        batch_op.drop_index(batch_op.f('ix_vocabulary_items_language_id'))

    op.drop_table('vocabulary_items')
    with op.batch_alter_table('user_module_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_module_state_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_module_state_module_id'))

    op.drop_table('user_module_state')
    with op.batch_alter_table('srs_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_srs_reviews_user_id'))

    op.drop_table('srs_reviews')
    with op.batch_alter_table('sentence_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sentence_links_sentence_id'))

    op.drop_table('sentence_links')
    with op.batch_alter_table('review_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_answers_session_id'))

    op.drop_table('review_answers')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_module_id'))

    op.drop_table('lessons')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_user_id'))

    op.drop_table('journal_entries')
    op.drop_table('intermissions')
    with op.batch_alter_table('grammar_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grammar_points_module_id'))
        batch_op.drop_index(batch_op.f('ix_grammar_points_language_id'))

    op.drop_table('grammar_points')
    with op.batch_alter_table('xp_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_xp_events_user_id'))

    op.drop_table('xp_events')
    op.drop_table('user_widget_layouts')
    with op.batch_alter_table('user_synonyms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_synonyms_user_id'))

    op.drop_table('user_synonyms')
    op.drop_table('user_settings')
    with op.batch_alter_table('user_item_progress', schema=None) as batch_op:
        batch_op.drop_index('ix_uip_due')

    op.drop_table('user_item_progress')
    with op.batch_alter_table('user_item_practice_stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_item_practice_stages_user_id'))

    op.drop_table('user_item_practice_stages')
    op.drop_table('user_changelog_reads')
    op.drop_table('subscriptions')
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sentences_language_id'))

    op.drop_table('sentences')
    with op.batch_alter_table('review_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_sessions_user_id'))

    op.drop_table('review_sessions')
    op.drop_table('profiles')
    with op.batch_alter_table('practice_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_sessions_user_id'))

    op.drop_table('practice_sessions')
    with op.batch_alter_table('points_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_points_events_user_id'))

    op.drop_table('points_events')
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modules_language_id'))

    op.drop_table('modules')
    op.drop_table('journal_prompts')
    op.drop_table('feedback_tickets')
    op.drop_table('deletion_approvals')
    with op.batch_alter_table('content_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_versions_table_name'))
        batch_op.drop_index(batch_op.f('ix_content_versions_row_id'))

    op.drop_table('content_versions')
    op.drop_table('content_imports')
    op.drop_table('changelog_entries')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))

    op.drop_table('auth_sessions')
    with op.batch_alter_table('admin_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_audit_logs_actor_id'))

    op.drop_table('admin_audit_logs')
    op.drop_table('users')
    op.drop_table('languages')
    op.drop_table('dashboard_widgets')
    op.drop_table('audio_assets')
    content_status_enum.drop(op.get_bind(), checkfirst=True)
    user_role_enum.drop(op.get_bind(), checkfirst=True)
    user_status_enum.drop(op.get_bind(), checkfirst=True)
    item_type_enum.drop(op.get_bind(), checkfirst=True)
    practice_category_enum.drop(op.get_bind(), checkfirst=True)
    leech_state_enum.drop(op.get_bind(), checkfirst=True)
    curriculum_mode_enum.drop(op.get_bind(), checkfirst=True)
    lesson_kind_enum.drop(op.get_bind(), checkfirst=True)
    gram_gender_enum.drop(op.get_bind(), checkfirst=True)
    article_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
