"""audio settings

Revision ID: 70e897feb3f0
Revises: 9a4260447763
Create Date: 2026-07-22 06:25:27.420820
"""
from alembic import op
import sqlalchemy as sa
import app.db.base  # custom GUID type used by columns


revision = '70e897feb3f0'
down_revision = '9a4260447763'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        # server_default is required: these are NOT NULL and user_settings
        # already has rows, which would otherwise fail the constraint.
        batch_op.add_column(sa.Column('audio_autoplay', sa.Boolean(),
                                      nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('audio_voice', sa.String(length=60),
                                      nullable=False, server_default=''))
        batch_op.add_column(sa.Column('audio_rate', sa.Numeric(precision=3, scale=2),
                                      nullable=False, server_default='1.0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('audio_rate')
        batch_op.drop_column('audio_voice')
        batch_op.drop_column('audio_autoplay')

    # ### end Alembic commands ###
